[package]
name = "rusty-ffmpeg-meta"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
rusty_ffmpeg = "0.16.1"
html-escape = "0.2"
urlencoding = "2"
serde = { version = "1", features = ["derive"] }
clap = { version = "4", features = ["derive"] }
dirs = "5"
toml = "0.8"
