[package]
name = "rusty-ffmpeg-meta"
version = "0.3.0"
edition = "2021"
license = "MIT"

[dependencies]
html-escape = "0.2"
urlencoding = "2"
serde = { version = "1", features = ["derive"] }
clap = { version = "4", features = ["derive"] }
dirs = "5"
toml = "0.8"
ffmpeg-next = "7.1.0"
